
# ==================             #===================#
# L2jnet 2.0 - Config             # Database Settings # 
# ==================             #===================#



# --------------------
# Database Information
# --------------------

# Define MySQL Driver
Driver = com.mysql.jdbc.Driver

# here you have some more drivers: 
# Driver = org.hsqldb.jdbcDriver
# Driver = com.microsoft.sqlserver.jdbc.SQLServerDriver

# Define MySQL Driver URL.
URL = jdbc:mysql://l2mariadb/l2jdb

# here you have some more urls: 
# URL = jdbc:hsqldb:hsql://localhost/l2jnet_db
# URL = jdbc:sqlserver://localhost/database = L2jnet_db/user = sa /password = (your pass)

# Your login to Database (default = root)
Login = root

# Your password to database (default = root)
Password = root

# Define how many connections are allowed on your database.
MaximumDbConnections = 10
