
# ==================              #=================#
# L2jnet 2.0 - Config              # SECURITY CENTER # 
# ==================              #=================#
                                                


# FloodProtection for Gameserver security.. (time in ms)
EnableFloodProtection = true

FastConnectionLimit = 15
NormalConnectionTime = 700
FastConnectionTime = 350
MaxConnectionPerIP = 50