
# ==================             ##########################
# L2jnet 2.0 - Config             # Logging Debug Settings # 
# ==================             ##########################

# Enable Debug on Console
Developer = false